
### Setup
```{r}
library(dplyr)
library(ggplot2)
library(readxl)
library(tidyr)

def <- read_excel('cyclonesFootball2020.xlsx', sheet = 'Defensive')
off <- read_excel('cyclonesFootball2020.xlsx', sheet = 'Offensive')
kikr <- read_excel('cyclonesFootball2020.xlsx', sheet = 'Kick Returns')
kik <- read_excel('cyclonesFootball2020.xlsx', sheet = 'Kicking')
bio <- read_excel('cyclonesFootball2020.xlsx', sheet = 'Biography')


```

### Part One

### Question 3
```{r}
bio %>%
  separate(Height, c('Height_feet', 'Height_inches')) %>%
  mutate(Height_feet = as.integer(Height_feet), 
         Height_inches = as.integer(Height_inches)) %>%
  mutate(Height = (Height_inches + (Height_feet * 12))) %>%
  select(-Height_inches, -Height_feet)
```

### Part Two

### Question 4
```{r}
d <- bio %>%
  separate(Hometown, c('Hometown_city', 'Hometown_state'), sep = ', ')
```

### Question 5
```{r}
d %>%
  select(Hometown_state) %>%
  group_by(Hometown_state) %>%
  summarise(count = n())
```

Nice Work -Desmond

Thanks Desmond! -Mario